[package]
version = "0.1.0"
edition = "2024"
name = "ttf-view"
description = "A TrueType/OpenType font parsing/viewing library, and also a CLI tool."
authors = ["Chasmical <kaz@chsm.dev>"]
keywords = []
categories = []
repository = "https://github.com/Chasmical/ttf-edit"
license = "MIT OR Apache-2.0"
readme = "../../README.md"

[dependencies]
chrono = "0.4.45"
color-print = { version = "0.3.7", optional = true }
encoding_rs = { version = "0.8.35", optional = true }
thiserror = "2.0.19"
zerocopy = "0.8.55"

[features]
default = ["non-standard-encodings"]
non-standard-encodings = ["dep:encoding_rs"]

# Feature to enable ttf-view CLI app's dependencies
cli = ["dep:color-print"]

[[bin]]
name = "ttf-view"
required-features = ["cli"]
